#!/usr/bin/env python3
"""Gradient-kernel hot-spot check.

Purpose: demonstrate that the hot-spot (E_v ~ E_Z crossing) enhancement of
the spin-valley response is generated by the four-level dynamics and does
NOT require an explicit resonance window in the coupling kernel. Under the
gradient-only ansatz A -- whose lambda_sv(x) contains no function of
E_v - E_Z -- the valley leakage collapses by more than two orders of
magnitude when the pocket minimum is raised above the local Zeeman energy
so that no E_v = E_Z crossing exists. The control is shape-preserving:
the Gaussian pocket is kept (Ev_min = 70 ueV vs the total-field E_Z range
of 58.6-64.8 ueV on this geometry), so only the existence of the crossing
changes, not the presence of a pocket. The deterministic (charge-noise-off)
M1V branch is reported, isolating the coherent four-level dynamics. A
lambda_sv = 0 control shows that the crossing response requires the
off-diagonal coupling (it is not produced by the Delta_v valley dynamics
alone).

This supports the Model-section passage on the physical admissibility of
the gradient-only kernels (see the paragraph beginning "One might ask
whether the gradient-only kernels ..."). The numbers below are a
supporting check only; they are not reported in the paper.

Run:
    PYTHONPATH=. python reproduce/phase5_gradient_kernel_hotspot_check.py

Reference values, corrected valley ordering H_v = -(eps_v/2) tau_z.
Measured 2026-09-02 on the frozen producer closure
(atlas 78daa7a9, crossterm a250a434, observables 880e02f9, minimum d610af7c);
Linux x86-64, float64, deterministic M1V; 2 min 3 s on CPU, multithreaded:
    lambda = 0      : crossing P_v_dia ~ 3.30e-05 , non-crossing ~ 4.04e-05
    lambda = 1 ueV  : crossing P_v_dia ~ 4.15e-01 , non-crossing ~ 1.70e-03
    crossing/non-crossing ratio at lambda = 1 ueV : ~ 244

Archived values under the pre-correction ordering H_v = +(eps_v/2) tau_z, kept
for provenance. They are a different convention, not an earlier measurement of
the same quantity, and must not be joined to the set above with an arrow:
    lambda = 1 ueV  : crossing P_v_dia ~ 4.52e-01 , non-crossing ~ 1.79e-03
    crossing/non-crossing ratio at lambda = 1 ueV : ~ 252

The lambda = 0 legs are identical to the precision reported, which is
structural rather than lucky. At zero coupling the valley sector evolves alone,
so flipping the sign of tau_z while the readout branch swaps with it is the
relabelling U = tau_x; starting in one branch and measuring the other returns
the same number in either direction. Gate C1-G2 verifies that identity to
3.5e-18. The lambda != 0 legs move by 5-8% because sigma_x (x) tau_x couples
the sectors and the spin Zeeman term breaks the symmetry.

Pass criteria (loose, cross-platform):
    both lambda=0 values < 1e-3
    lambda=1 crossing P_v_dia > 0.1
    lambda=1 crossing/non-crossing ratio > 50
"""
from __future__ import annotations

import sys

from reproduce.phase5_sensitivity_atlas import make_ff, GEOM0
from reproduce.phase4p6_crossterm import run_one_condition, OneOverFNoise
from constants import Defaults

E_C = 1.602176634e-19  # C


def leakage_m1v(lambda_uev: float, ev_min_uev: float) -> float:
    ff = make_ff(**GEOM0)
    noise = OneOverFNoise(sigma_total=Defaults.sigma_dx_m, alpha=1.0,
                          f_low=1e3, f_high=1e7)
    pocket_width = 30e-9
    v = 10.0
    T = (8 * pocket_width) / v
    R = run_one_condition(
        v=v, case_label="hotspot_check", pocket_x_center=0.0,
        lambda_0=lambda_uev * 1e-6 * E_C, coupling_model="A", n_real=3,
        noise=noise, ff=ff,
        eps_v_baseline=100e-6 * E_C, eps_v_min=ev_min_uev * 1e-6 * E_C,
        pocket_width=pocket_width, Delta_v=0.5e-6 * E_C,
        N_max=500, base_seed=1234, T_traj_for_noise=T,
        ez_convention="total-local", profile_norm="prefactor")
    return float(R["M1V"]["P_v_dia"]["mean"])


def main() -> int:
    print("gradient-kernel hot-spot check (ansatz A, total-local/prefactor)")
    print("  deterministic M1V branch; shape-preserving control")
    print("  geometry=baseline, centered pocket, v=10 m/s")
    print("  crossing: Ev_min=5 ueV | non-crossing: Ev_min=70 ueV "
          "(pocket kept; E_Z range 58.6-64.8 ueV)\n")

    p0_cross = leakage_m1v(0.0, 5.0)
    p0_nc = leakage_m1v(0.0, 70.0)
    print(f"  lambda=0     : crossing P_v_dia = {p0_cross:.3e}   "
          f"non-crossing P_v_dia = {p0_nc:.3e}")

    p1_cross = leakage_m1v(1.0, 5.0)
    p1_nc = leakage_m1v(1.0, 70.0)
    ratio = p1_cross / p1_nc
    print(f"  lambda=1 ueV : crossing P_v_dia = {p1_cross:.3e}   "
          f"non-crossing P_v_dia = {p1_nc:.3e}")
    print(f"  crossing/non-crossing ratio (lambda=1 ueV) = {ratio:.1f}\n")

    ok = (p0_cross < 1e-3 and p0_nc < 1e-3
          and p1_cross > 0.1 and ratio > 50.0)
    print(f"hot-spot-from-dynamics check: {'PASS' if ok else 'FAIL'}")
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
